services:
  db:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Markora
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: securepass
    ports:
      - "5050:80"
    volumes:
      - ./database/pgadmin_backups:/var/lib/pgadmin/storage/
    depends_on:
      - db

volumes:
  postgres_data:
